String testText="Start with a hook that grabs attention and sets the tone for the review. Mention the name of the restaurant, café, or food item and why you decided to try it"
                    "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype"
                    "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype"
                    "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype"
                    "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype"
                    "attention and sets the tone for the review. Mention the name of the restaurant, café, or food item and why you decided to try it"
                    "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype"
                    "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype"
                    "attention and sets the tone for the review. Mention the name of the restaurant, café, or food item and why you decided to try it"
                "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype"
                    "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype"
                    "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype"
                    "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype"
                    "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype"
                    "Nestled in the heart of downtown, Bella Italia promises authentic Italian flavors, and I couldn’t resist the temptation to find out if it lives up to the hype";